import type { Metadata } from "next";
import { getStaticPageMetadata } from "@/lib/seo";
import { SITE_NAME } from "@/lib/utils";

export const metadata: Metadata = getStaticPageMetadata(
  "Terms of Service",
  `${SITE_NAME} terms of service. Simple, fair, and transparent usage terms.`
);

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
        Terms of Service
      </h1>
      <p className="text-sm text-muted-foreground mb-8">
        Last updated: September 2, 2026
      </p>

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
        <section>
          <h2>Acceptance</h2>
          <p>
            By using {SITE_NAME}, you agree to these terms. If you do not agree,
            please do not use the service.
          </p>
        </section>

        <section>
          <h2>Use of Service</h2>
          <p>
            {SITE_NAME} provides free online tools and calculators. You may use
            these tools for any lawful purpose. You are responsible for the
            accuracy and appropriateness of your inputs and outputs.
          </p>
        </section>

        <section>
          <h2>No Warranty</h2>
          <p>
            All tools are provided &quot;as is&quot; without warranty of any kind.
            While we strive for accuracy, results should be verified independently
            for critical decisions.
          </p>
        </section>

        <section>
          <h2>Intellectual Property</h2>
          <p>
            The {SITE_NAME} website, design, and code are our intellectual property.
            Tool results generated by you are yours to use freely.
          </p>
        </section>

        <section>
          <h2>Limitation of Liability</h2>
          <p>
            {SITE_NAME} and its creators shall not be liable for any damages arising
            from the use of or inability to use the service.
          </p>
        </section>
      </div>
    </div>
  );
}
