/**
 * Robots.txt Generator business logic.
 * Generates properly formatted robots.txt files.
 */

export interface RobotsRule {
  userAgent: string[];
  allow: string[];
  disallow: string[];
  crawlDelay?: number;
}

export interface RobotsConfig {
  rules: RobotsRule[];
  sitemapUrl?: string;
  host?: string;
}

const DEFAULT_RULES: RobotsRule[] = [
  {
    userAgent: ["*"],
    allow: ["/"],
    disallow: ["/admin/", "/private/"],
  },
];

export function generateRobotsTxt(config: RobotsConfig): string {
  const lines: string[] = [];

  // Comment header
  lines.push("# robots.txt — Generated by ToolNest Robots.txt Generator");
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push("");

  // Rules
  for (const rule of config.rules) {
    const agents = rule.userAgent;

    for (const agent of agents) {
      lines.push(`User-agent: ${agent}`);
    }

    for (const path of rule.allow) {
      if (path) lines.push(`Allow: ${path}`);
    }

    for (const path of rule.disallow) {
      if (path) lines.push(`Disallow: ${path}`);
    }

    if (rule.crawlDelay !== undefined && rule.crawlDelay > 0) {
      lines.push(`Crawl-delay: ${rule.crawlDelay}`);
    }

    lines.push("");
  }

  // Sitemap
  if (config.sitemapUrl) {
    lines.push(`Sitemap: ${config.sitemapUrl}`);
  }

  // Host
  if (config.host) {
    lines.push(`Host: ${config.host}`);
  }

  return lines.join("\n").trim() + "\n";
}

export function parseRulesText(text: string): string[] {
  return text
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

export const COMMON_DISALLOW_PATHS = [
  "/admin/",
  "/private/",
  "/tmp/",
  "/cgi-bin/",
  "/wp-admin/",
  "/wp-includes/",
  "/search/",
  "/tag/",
  "/author/",
];

export const COMMON_USER_AGENTS = ["*", "Googlebot", "Bingbot", "Slurp", "DuckDuckBot"];
